networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

# INSTALL a staging "intermediate" STAGING LE certificate for windows
# https://github.com/letsencrypt/website/blob/main/static/certs/staging/2024/e5.pem
#
# WINDOWS 
# certutil -addstore -f "Root" e5.pem
#
# certmgr (to veiw certificate)

  
services:
    caddy:
        build:
            context: .
            dockerfile_inline: |
                FROM golang:alpine

                RUN apk add git

                WORKDIR /opt

                RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

                RUN xcaddy build \
                    --with github.com/mholt/caddy-l4 \
                    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
                    --with github.com/abiosoft/caddy-yaml \
                    --with github.com/abiosoft/caddy-json-schema

                ENTRYPOINT ["/opt/caddy"]

                CMD ["docker-proxy"]
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        labels:
            - caddy.acme_ca=https://acme-staging-v02.api.letsencrypt.org/directory
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy_data:/data
        restart: unless-stopped

