networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
  
services:
    caddy:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy_data:/data
        restart: unless-stopped

